Got to the host, now for the hard part :|
```
[info] Running org.scalareflect.reflectdoc.ReflectDoc
Hi! прывітанне! Bună ziua! Bonjour! Grüezi! Ciao!
[error] (run-main-2) scala.NotImplementedError: an implementation is missing
scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
	at scala.reflect.semantic.RefOps$SemanticTermRefOps.defns(Refs.scala:23)
	at reflectdoc.tools.nsc.doc.model.ModelFactory.<init>(ModelFactory.scala:86)
	at reflectdoc.tools.nsc.doc.DocFactory$$anon$1.<init>(DocFactory.scala:48)
	at reflectdoc.tools.nsc.doc.DocFactory.makeUniverse(DocFactory.scala:48)
	at reflectdoc.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:88)
	at reflectdoc.tools.nsc.doc.DocFactory.document(DocFactory.scala:100)
	at org.scalareflect.reflectdoc.ReflectDoc$.process(Main.scala:30)
	at org.scalareflect.reflectdoc.ReflectDoc$.main(Main.scala:45)
	at org.scalareflect.reflectdoc.ReflectDoc.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
[trace] Stack trace suppressed: run last reflectdoc-runtime/compile:run for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last reflectdoc-runtime/compile:run for the full output.
[error] (reflectdoc-runtime/compile:run) Nonzero exit code: 1
[error] Total time: 0 s, completed May 31, 2014 12:35:43 AM
```