Ready for the runtime host
```
[info] Running org.scalareflect.reflectdoc.ReflectDoc
Hi! прывітанне! Bună ziua! Bonjour! Grüezi! Ciao!
[error] (run-main-2) scala.NotImplementedError: an implementation is missing
scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
	at org.scalareflect.reflectdoc.ReflectDoc$.createReflectionHost(Main.scala:16)
	at org.scalareflect.reflectdoc.ReflectDoc$.process(Main.scala:28)
	at org.scalareflect.reflectdoc.ReflectDoc$.main(Main.scala:44)
	at org.scalareflect.reflectdoc.ReflectDoc.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```